### ISSUE TITLE
tap OK button make a blank screen after AutoClose elapsed time

### ISSUE THREAD

**Issue by LuisCarrizo** [belovance/QuickAlert#18]
**Describe the bug**
In flutter, when user tap Quick Alert´s OK button, the quickAlert dialog is closed, but after the time specified in the autoCloseDuration property, the screen became black. 

To test the bug  I wrote a very simple project based on counter project.

pubspec.yaml looks like this:

```
name: debug01
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-128.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  quickalert: ^1.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
```

I´ve added a sucess quickAlert after _counter++; on _incrementCounter() method, with 5 seconds autoCloseDuration

```
  void _incrementCounter() {
    setState(() {
      _counter++;
      // quick alert added for debug
      QuickAlert.show(
        context: context,
        type: QuickAlertType.success,
        text: 'Transaction Completed Successfully!',
        autoCloseDuration: const Duration(seconds: 5),
      );
    });
  }
```
The problem is that when user tap Quick Alert´s OK button, the quickAlert dialog is closed, but after the time specified in the autoCloseDuration property, the screen became black. 
No debug console message was shown.
Tested on:

- windows desktop
- chrome web
- edge web
- android emulator
- android device

**To Reproduce**
1. set autoCloseDuration property of a quickAlert dialog with *n* seconds
2. show the quickAlert dialog
3. click OK button 
4. Screen became black after *n* seconds

**Expected behavior**
OK button should close the quickAlert Dialog and interrupt autoClose

**Desktop ():**
 - OS: windows 10
 - Browser edge
 - Version 113.0.1774.50

**Android emulator
- Device Pixel 6 Pro API 33
 - OS: android 13

**Smartphone :**
 - Device: redmi 6
 - OS: android 9

**Screenshots**
video attached

https://github.com/belovance/QuickAlert/assets/33325595/ecaea8f7-c9cb-4288-a44e-241c8daa66bd
